### ISSUE TITLE
Use a repository with a gh-pages branch

### ISSUE THREAD

**Issue by joezeng** [Jcw87/Jcw87.github.io#1]
If you plan on having different projects on your github.io, it would probably be a better idea to create a separate repository for "Sans", then make a gh-pages branch to make it load at the same URL. Otherwise, all the commits from your various projects will end up interfering with each other.

**Comment by Jcw87** [comment]
That would make more sense if I put the source files in a repository, but I have not. I was more or less just looking for a quick place to put this online. I also have no idea if I'm gonna put anything else up here later, so it might not be an issue anyway.

By the way, your endless sans game was sort of the 'inspiration' to make this one. It wouldn't be the first time I saw someone else's game clone project and had an urge to make my own.

**Comment by joezeng** [comment]
I'd actually like to help you develop your version, if you're up to it. If you could upload the Construct 2 project files, I could download the community version and look at stuff, maybe implement a time counter or something.

**Comment by Jcw87** [comment]
Alright, I put it up [here](https://github.com/Jcw87/c2-sans-fight). I haven't added very many comments yet, and there's a couple things that could use some revising.

Though, I'm pretty sure you won't be able to use the free version of Construct 2. The free version is limited to projects with 100 events or less, while I currently have 644.

**Comment by joezeng** [comment]
Huh. Didn't know that part.

**Comment by Jcw87** [comment]
Anyways, I'm gonna close this issue, as it has been addressed. If you would like to see more features (such as the time counter you mentioned), you can open a new issue on the new repository.
